stages:
  - build
  - deploy

build:
  stage: build
  image: docker
  services:
    - docker:dind
  before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t micmunger/8cld201:web ./Web
    - docker build --pull -t micmunger/8cld201:db ./DB
    - docker build --pull -t micmunger/8cld201:complexe ./Complexe

  only:
    - main

deploy:
  stage: deploy
  image: docker
  services:
    - docker:dind
  before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker push micmunger/8cld201:web
    - docker push micmunger/8cld201:db
    - docker push micmunger/8cld201:complexe

  only:
    - main