build image:
  image: docker
  services:
    - docker:dind
  before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t micmunger/8cld201:web ./Web
    - docker push micmunger/8cld201:web
    - docker build --pull -t micmunger/8cld201:db ./DB
    - docker push micmunger/8cld201:db
    - docker build --pull -t micmunger/8cld201:complexe ./Complexe
    - docker push micmunger/8cld201:complexe

  only:
    - main

#deploy image:
